# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Aclevo Blog
email: info@aclevo.xyz
description: > # this means to ignore newlines until "baseurl:"
  The Official Aclevo Blog
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://aclv.github.io/blog" # the base hostname & protocol for your site
twitter_username: aclevo
github_username:  aclv

# Build settings
markdown: kramdown
